# SPDX-FileCopyrightText: OpenTalk GmbH <mail@opentalk.eu>
#
# SPDX-License-Identifier: MIT OR Apache-2.0

[workspace]
members = ["crates/*"]
resolver = "2"

[workspace.package]
description = "Use derive to create HTTP requests"
edition = "2024"
license = "MIT OR Apache-2.0"
publish = true
repository = "https://gitlab.opencode.de/opentalk/libs/http-request-derive"

[workspace.dependencies]
async-trait = "0.1.82"
bytes = "1"
darling = "0.23.0"
http = "1"
http-request-derive = { version = "0.5.0", path = "crates/http-request-derive" }
http-request-derive-client = { version = "0.2.0", path = "crates/http-request-derive-client" }
http-request-derive-macros = { version = "0.2.1", path = "crates/http-request-derive-macros" }
httptest = "0.16"
pretty_assertions = "1"
pretty_env_logger = "0.5"
proc-macro2 = "1.0.81"
quote = "1.0.36"
reqwest = { version = "0.12", default-features = false }
serde = "1"
serde_json = "1"
serde_url_params = "0.2"
snafu = "0.8"
strum = "0.27.0"
syn = "2.0.60"
tokio = "1.0"
url = "2"
