# SPDX-FileCopyrightText: OpenTalk GmbH <mail@opentalk.eu>
#
# SPDX-License-Identifier: MIT OR Apache-2.0

[workspace]
members = ["crates/*"]
resolver = "2"

[workspace.package]
description = "Use derive to create HTTP requests"
edition = "2021"
license = "MIT OR Apache-2.0"
publish = true
repository = "https://gitlab.opencode.de/opentalk/libs/http-request-derive"

[workspace.dependencies]
http-request-derive-macros = { version = "0.0.0-dev", path = "crates/http-request-derive-macros" }
