# SPDX-FileCopyrightText: OpenTalk GmbH <mail@opentalk.eu>
#
# SPDX-License-Identifier: MIT OR Apache-2.0

[package]
description.workspace = true
edition.workspace = true
license.workspace = true
name = "http-request-derive-macros"
publish.workspace = true
repository.workspace = true
version = "0.0.0-dev"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[lib]
proc-macro = true

[dependencies]
darling.workspace = true
proc-macro2.workspace = true
quote.workspace = true
strum = { workspace = true, features = ["derive"] }
syn.workspace = true
