# SPDX-FileCopyrightText: OpenTalk GmbH <mail@opentalk.eu>
#
# SPDX-License-Identifier: MIT OR Apache-2.0

[package]
description.workspace = true
edition.workspace = true
license.workspace = true
name = "http-request-derive-macros"
publish.workspace = true
repository.workspace = true
version = "0.0.0-dev"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[lib]
proc-macro = true

[dependencies]
darling = "0.20.8"
proc-macro2 = "1.0.81"
quote = "1.0.36"
strum = { version = "0.26.2", features = ["derive"] }
syn = "2.0.60"
